package com.example.etl.ingestion.handlers

import com.example.etl.config.JobConfig
import com.example.etl.sql.{SqlParserService, LogicalPlanValidator}
import com.example.etl.logic.Scd2LogicUtil
import com.example.etl.reconciliation.ReconciliationService
import org.apache.spark.sql.{DataFrame, SparkSession, SaveMode, Dataset}
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types.{TimestampType, StructType, StructField}
import org.apache.log4j.Logger
import java.sql.Timestamp
import java.time.Instant
import scala.util.parsing.json.JSON

object Scd2LogicHandler {
  @transient lazy val logger: Logger = Logger.getLogger(getClass.getName)
  def execute(jobConfig: JobConfig, spark: SparkSession): (Option[Long], Option[Long]) = {
    logger.info(s"Executing SCD2 ingestion for job_name: ${jobConfig.job_name}")
    val procTs=Timestamp.from(Instant.now()); val highTs=Timestamp.valueOf("9999-12-31 23:59:59")
    var iSrcCnt:Option[Long]=None; var tSrcCnt:Option[Long]=None; var tgtCurCnt:Option[Long]=None; var rWrittenCnt:Option[Long]=None
    val scdCols=Scd2LogicUtil.ScdColumnNames(skIdCol=jobConfig.scd2_surrogate_key_column.getOrElse("sk_id"),validFromCol=jobConfig.scd2_valid_from_column.getOrElse("valid_from_ts"),validToCol=jobConfig.scd2_valid_to_column.getOrElse("valid_to_ts"),versionCol=jobConfig.scd2_version_column.getOrElse("version"),isCurrentCol=jobConfig.scd2_current_flag_column.getOrElse("is_current"),changeTypeCol="change_type")
    if(jobConfig.source_connection_details.isEmpty) throw new IllegalArgumentException(s"Source connection details required for ${jobConfig.job_name}")
    var rawSrcDF: DataFrame = null; jobConfig.source_type.toUpperCase match {case "FILE"=>val fmt=jobConfig.source_format.getOrElse(throw new IllegalArgumentException("src_fmt required")).toLowerCase;val rdr=spark.read.format(fmt);jobConfig.source_format_options.foreach(o=>JSON.parseFull(o) match {case Some(m:Map[String,String])=>rdr.options(m) case _=>});jobConfig.source_schema.foreach(s=>rdr.schema(s));rawSrcDF=rdr.load(jobConfig.source_connection_details.get) case o=>throw new UnsupportedOperationException(s"Source type '$o' not supported for SCD2.")}
    if(jobConfig.audit_level.toUpperCase!="NONE") try iSrcCnt=Some(rawSrcDF.count()) catch {case e:Exception=>logger.warn(s"Could not count raw src for ${jobConfig.job_name}: ${e.getMessage}",e)}\n    logger.info(s"Raw source read for ${jobConfig.job_name}. Recs: ${iSrcCnt.getOrElse("N/A")}")
    val tSrcDF=jobConfig.sql_logic match {case Some(s) if s.trim.nonEmpty =>{val rView=jobConfig.job_name+"_raw_scd_src";rawSrcDF.createOrReplaceTempView(rView);logger.info(s"Registered raw src view '$rView' for ${jobConfig.job_name}"); val pE=SqlParserService.parse(s,spark);val p=pE match{case Right(pl)=>pl case Left(e)=>throw new RuntimeException(s"SQL parse failed for ${jobConfig.job_name}: $e")}; LogicalPlanValidator.validate(p) match {case Right(_)=> case Left(e)=>throw new RuntimeException(s"Plan invalid for ${jobConfig.job_name}: ${e.mkString(";")}")}; try Dataset.ofRows(spark,p) catch {case e:Exception=>throw new RuntimeException(s"Error exec plan for ${jobConfig.job_name}: ${e.getMessage}",e)}} case _=>logger.info(s"No sql_logic, using raw source for ${jobConfig.job_name}.");rawSrcDF}\n    if(jobConfig.audit_level.toUpperCase!="NONE") try tSrcCnt=Some(tSrcDF.count()) catch {case e:Exception=>logger.warn(s"Could not count tSrc for ${jobConfig.job_name}: ${e.getMessage}",e)}\n    logger.info(s"Transformed source for SCD2 for ${jobConfig.job_name}. Recs: ${tSrcCnt.getOrElse("N/A")}")
    val tgtPath=jobConfig.target_table_or_path
    val tgtCurDF:DataFrame=try {val tFull=spark.read.format(jobConfig.target_format.getOrElse("parquet")).load(tgtPath);tFull.filter(col(scdCols.isCurrentCol)===true)} catch {case e:org.apache.spark.sql.AnalysisException if e.getMessage.toLowerCase.contains("path does not exist") =>logger.warn(s"Target $tgtPath not found for ${jobConfig.job_name}. Initial load."); val s=StructType(tSrcDF.schema.fields++Seq(StructField(scdCols.skIdCol,org.apache.spark.sql.types.LongType,false),StructField(scdCols.validFromCol,TimestampType,false),StructField(scdCols.validToCol,TimestampType,false),StructField(scdCols.versionCol,org.apache.spark.sql.types.IntegerType,false),StructField(scdCols.isCurrentCol,org.apache.spark.sql.types.BooleanType,false),StructField(scdCols.changeTypeCol,org.apache.spark.sql.types.StringType,true)));spark.createDataFrame(spark.sparkContext.emptyRDD[org.apache.spark.sql.Row],s) case e:Exception=>throw new RuntimeException(s"Error reading target for ${jobConfig.job_name}: ${e.getMessage}",e)}\n    if(jobConfig.audit_level.toUpperCase!="NONE") try tgtCurCnt=Some(tgtCurDF.count()) catch {case e:Exception=>logger.warn(s"Could not count tgtCur for ${jobConfig.job_name}: ${e.getMessage}",e)}\n    logger.info(s"Current target read for ${jobConfig.job_name}. Active: ${tgtCurCnt.getOrElse("N/A")}")
    val nkCols=jobConfig.scd2_natural_keys.getOrElse(throw new IllegalArgumentException(s"scd2_natural_keys required for ${jobConfig.job_name}")).split(',').map(_.trim).filter(_.nonEmpty); if(nkCols.isEmpty) throw new IllegalArgumentException(s"scd2_natural_keys empty for ${jobConfig.job_name}")
    val srcBusHashCols=tSrcDF.columns.filterNot(nkCols.contains).toSeq
    val delAbs=jobConfig.job_properties.flatMap(JSON.parseFull(_).collect{case m:Map[String,String]=>m.get("scd2_handle_deletes_by_absence")}.flatten.map(_.toBoolean)).getOrElse(false)\n    val catRecs=Scd2LogicUtil.categorizeAndDetectChanges(tSrcDF,tgtCurDF,nkCols,jobConfig.scd2_change_tracking_column,srcBusHashCols,delAbs,spark)\n    val finalOutDF=Scd2LogicUtil.generateScdOutputRecords(catRecs,tSrcDF.columns.toSeq,tgtCurDF.columns.toSeq,nkCols,scdCols,procTs,highTs,spark)\n    logger.info(s"Final SCD output generated for ${jobConfig.job_name}.")
    val wr=finalOutDF.write.mode(SaveMode.Append);jobConfig.target_format.foreach(f=>wr.format(f.toLowerCase));jobConfig.target_format_options.foreach(o=>JSON.parseFull(o)match{case Some(m:Map[String,String])=>wr.options(m) case _=>});jobConfig.partitioning_columns.foreach(pc=>{val c=pc.split(',').map(_.trim).filter(_.nonEmpty);if(c.nonEmpty)wr.partitionBy(c:_*) });wr.save(tgtPath);logger.info(s"SCD records written for ${jobConfig.job_name}.")
    if(jobConfig.audit_level.toUpperCase!="NONE") try rWrittenCnt=Some(finalOutDF.count()) catch {case e:Exception=>logger.warn(s"Could not count final output for ${jobConfig.job_name}: ${e.getMessage}",e)}\n    if(jobConfig.reconciliation_enabled.equalsIgnoreCase("Y")&&jobConfig.reconciliation_config.exists(_.trim.nonEmpty)){logger.info(s"Reconciliation for ${jobConfig.job_name} (SCD2)... "); try{val sRecon=tSrcDF;val tFmt=jobConfig.target_format.getOrElse("parquet");val curTgtSnap=spark.read.format(tFmt).load(tgtPath).filter(col(scdCols.isCurrentCol)===true);val rep=ReconciliationService.executeChecks(jobConfig.job_name,sRecon,curTgtSnap,jobConfig.reconciliation_config.get,spark);logger.info(s"Recon Report for ${jobConfig.job_name} (SCD2 - Current View): Status - ${rep.overallStatus}");rep.checkResults.foreach(cr=>logger.info(s"  Check:${cr.checkType},Status:${cr.status},Msg:${cr.message}"));if(rep.overallStatus!="PASS")logger.warn(s"Recon for ${jobConfig.job_name} (SCD2) status: ${rep.overallStatus}.")}catch{case e:Exception=>logger.error(s"Error during SCD2 recon for ${jobConfig.job_name}: ${e.getMessage}",e)}}\n    logger.info(s"SCD2 ingestion for ${jobConfig.job_name} completed. Records written/affected: ${rWrittenCnt.getOrElse("N/A")}");(tSrcCnt,rWrittenCnt)}\n}
