package com.example.etl.ingestion.handlers

import com.example.etl.config.JobConfig
import com.example.etl.sql.{SqlParserService, LogicalPlanValidator}
import com.example.etl.reconciliation.ReconciliationService
import com.example.etl.dq.{DataQualityService, DataQualityReport}
import com.example.etl.util.LoggingUtil // Import LoggingUtil
import org.apache.spark.sql.{DataFrame, SparkSession, SaveMode, Dataset}
import org.apache.spark.sql.catalyst.plans.logical.LogicalPlan
import org.apache.log4j.Logger
import scala.util.parsing.json.JSON

object WithLogicIngestionHandler {
  @transient lazy val logger: Logger = Logger.getLogger(getClass.getName)
  def execute(jobConfig: JobConfig, spark: SparkSession): (Option[Long], Option[Long], Option[DataQualityReport]) = {
    logger.info(s"Executing WITH_LOGIC ingestion for job_name: ${jobConfig.job_name}")
    var rReadCnt: Option[Long]=None; var rWrittenCnt: Option[Long]=None; var dqReportOpt: Option[DataQualityReport]=None
    var srcDF: DataFrame=null
    jobConfig.source_type.toUpperCase match {
      case "FILE" => val p=jobConfig.source_connection_details.getOrElse(throw new IllegalArgumentException(s"Src path req for FILE ${jobConfig.job_name}")); val f=jobConfig.source_format.getOrElse(throw new IllegalArgumentException("src_fmt req for FILE")).toLowerCase; val r=spark.read.format(f); jobConfig.source_format_options.foreach(o=>JSON.parseFull(o)match{case Some(m:Map[String,String])=>r.options(m)case _=>}); jobConfig.source_schema.foreach(s=>r.schema(s)); srcDF=r.load(p)
      case "HIVE_TABLE" => val t=jobConfig.source_connection_details.getOrElse(throw new IllegalArgumentException(s"Src table req for HIVE ${jobConfig.job_name}")); try srcDF=spark.table(t) catch {case e:Exception=>throw new RuntimeException(s"Fail read HIVE $t: ${e.getMessage}",e)}
      case o => throw new UnsupportedOperationException(s"Src type '$o' not supported.")
    }
    if(srcDF==null)throw new RuntimeException(s"Src DF not loaded for ${jobConfig.job_name}.")
    if(jobConfig.audit_level.toUpperCase!="NONE")try rReadCnt=Some(srcDF.count())catch{case e:Exception=>logger.warn(s"No count src ${jobConfig.job_name}:${e.getMessage}",e)}\n    logger.info(s"Src data read for ${jobConfig.job_name}. Recs:${rReadCnt.getOrElse("N/A")}")
    if(logger.isDebugEnabled){logger.debug(s"Schema srcDF ${jobConfig.job_name}:");srcDF.printSchema();logger.debug(s"Sample srcDF ${jobConfig.job_name} (masked):"); val sShow=jobConfig.log_masking_columns.filter(_.trim.nonEmpty).map(c=>LoggingUtil.maskDataFrame(srcDF,c.split(',').map(_.trim))).getOrElse(srcDF);sShow.show(5,false)}
    val viewName=jobConfig.job_name+"_src_input_logic";srcDF.createOrReplaceTempView(viewName);logger.info(s"Reg srcDF view '$viewName' for ${jobConfig.job_name}.")
    var sql=jobConfig.sql_logic.getOrElse(throw new IllegalArgumentException(s"sql_logic req for ${jobConfig.job_name}"));if(sql.trim.isEmpty)throw new IllegalArgumentException(s"sql_logic empty ${jobConfig.job_name}")
    val pref="spark.etl.param.";spark.conf.getAll.foreach{case(k,v)=>if(k.startsWith(pref)){val pN=k.substring(pref.length);sql=sql.replace(s"$${$pN}",v);logger.info(s"Replaced '$${$pN}' with '$v' in SQL for ${jobConfig.job_name}")}};logger.info(s"SQL for ${jobConfig.job_name} (subst, first 200):${sql.take(200)}")
    val pL=SqlParserService.parse(sql,spark).getOrElse(throw new RuntimeException("SQL parse fail"));LogicalPlanValidator.validate(pL) match { case Right(_) => /* Do nothing */ case Left(errs) => throw new RuntimeException(s"Plan invalid for ${jobConfig.job_name}: ${errs.mkString(";")}") }
    val tDF=try Dataset.ofRows(spark,pL)catch{case e:Exception=>throw new RuntimeException(s"Err from LP ${jobConfig.job_name}:${e.getMessage}",e)}\n    logger.info(s"TfmDF gen for ${jobConfig.job_name}.")
    if(logger.isDebugEnabled){logger.debug(s"Schema tfmDF ${jobConfig.job_name}:");tDF.printSchema();logger.debug(s"Sample tfmDF ${jobConfig.job_name} (masked):"); val tShow=jobConfig.log_masking_columns.filter(_.trim.nonEmpty).map(c=>LoggingUtil.maskDataFrame(tDF,c.split(',').map(_.trim))).getOrElse(tDF);tShow.show(5,false)}\n    val wr=tDF.write;jobConfig.target_format.foreach(f=>wr.format(f.toLowerCase));jobConfig.target_format_options.foreach(o=>JSON.parseFull(o)match{case Some(m:Map[String,String])=>wr.options(m)case _=>});jobConfig.partitioning_columns.foreach(pc=>{val c=pc.split(',').map(_.trim).filter(_.nonEmpty);if(c.nonEmpty)wr.partitionBy(c:_*) });val sm=jobConfig.target_write_mode.toLowerCase match{case "overwrite"=>SaveMode.Overwrite case "append"=>SaveMode.Append case "ignore"=>SaveMode.Ignore case "errorifexists"|"error"=>SaveMode.ErrorIfExists case _=>SaveMode.Overwrite};wr.mode(sm)
    val tgtId=jobConfig.target_table_or_path;jobConfig.target_type.toUpperCase match {case "HDFS"|"FILE"=>wr.save(tgtId) case "HIVE_TABLE"=>wr.saveAsTable(tgtId) case o=>throw new UnsupportedOperationException(s"Tgt type '$o' not supported.")}\n    logger.info(s"Data written to $tgtId for ${jobConfig.job_name}")
    var finalTgtDF:DataFrame=null; if(jobConfig.audit_level.toUpperCase!="NONE"||jobConfig.reconciliation_enabled.equalsIgnoreCase("Y")||jobConfig.dq_checks_enabled.equalsIgnoreCase("Y")){try{val fmt=jobConfig.target_format.getOrElse("parquet");finalTgtDF=jobConfig.target_type.toUpperCase match{case "HDFS"|"FILE"=>spark.read.format(fmt).load(tgtId) case "HIVE_TABLE"=>spark.table(tgtId) case _=>throw new RuntimeException("Cannot re-read tgt.")};if(jobConfig.audit_level.toUpperCase!="NONE"){rWrittenCnt=Some(finalTgtDF.count())}}catch{case e:Exception=>logger.warn(s"Could not re-read tgt for post-proc ${jobConfig.job_name}:${e.getMessage}",e)}}\n    if(jobConfig.reconciliation_enabled.equalsIgnoreCase("Y")&&jobConfig.reconciliation_config.exists(_.trim.nonEmpty)&&finalTgtDF!=null){logger.info(s"Recon for ${jobConfig.job_name}...");try{val rep=ReconciliationService.executeChecks(jobConfig.job_name,tDF,finalTgtDF,jobConfig.reconciliation_config.get,spark);logger.info(s"Recon Report ${jobConfig.job_name}:St-${rep.overallStatus}");rep.checkResults.foreach(cr=>logger.info(s" Ck:${cr.checkType},St:${cr.status},Msg:${cr.message}"));if(rep.overallStatus!="PASS")logger.warn(s"Recon ${jobConfig.job_name} st:${rep.overallStatus}.")}catch{case e:Exception=>logger.error(s"Err recon ${jobConfig.job_name}:${e.getMessage}",e)}}\n    if(jobConfig.dq_checks_enabled.equalsIgnoreCase("Y")&&jobConfig.dq_rules_config.exists(_.trim.nonEmpty)&&finalTgtDF!=null){logger.info(s"DQ for ${jobConfig.job_name} on tgt...");try{val dqRep=DataQualityService.applyChecks(jobConfig.job_name,finalTgtDF,jobConfig.dq_rules_config.get,spark);dqReportOpt=Some(dqRep);logger.info(s"DQ Report ${jobConfig.job_name}:St-${dqRep.overallStatus}");dqRep.rule_results.foreach(rr=>logger.info(s" DQ Rule:${rr.rule_name},St:${rr.status},FailCnt:${rr.failing_records_count.getOrElse("N/A")},Msg:${rr.message}"));if(dqRep.overallStatus=="FAIL"){logger.error(s"Crit DQ fail ${jobConfig.job_name}.Failing job.");throw new RuntimeException(s"Crit DQ fail ${jobConfig.job_name}.")}}catch{case e:RuntimeException if e.getMessage.startsWith("Crit DQ fail")=>throw e case e:Exception=>logger.error(s"Err DQ ${jobConfig.job_name}:${e.getMessage}",e);throw new RuntimeException(s"Err DQ subsystem ${jobConfig.job_name}",e)}}\n    logger.info(s"WITH_LOGIC ${jobConfig.job_name} completed. Written:${rWrittenCnt.getOrElse("N/A")}");(rReadCnt,rWrittenCnt,dqReportOpt)}\n}
