package com.example.etl.ingestion.handlers

import com.example.etl.config.JobConfig
import com.example.etl.sql.{SqlParserService, LogicalPlanValidator}
import com.example.etl.reconciliation.ReconciliationService
import org.apache.spark.sql.{DataFrame, SparkSession, SaveMode, Dataset}
import org.apache.log4j.Logger
import scala.util.parsing.json.JSON

object WithLogicIngestionHandler {
  @transient lazy val logger: Logger = Logger.getLogger(getClass.getName)
  def execute(jobConfig: JobConfig, spark: SparkSession): (Option[Long], Option[Long]) = {
    logger.info(s"Executing WITH_LOGIC ingestion for job_name: ${jobConfig.job_name}")
    var rReadCount: Option[Long] = None; var rWrittenCount: Option[Long] = None
    if(jobConfig.source_connection_details.isEmpty) throw new IllegalArgumentException(s"Source connection details required for ${jobConfig.job_name}")
    var srcDF: DataFrame = null
    jobConfig.source_type.toUpperCase match { case "FILE"=>val fmt=jobConfig.source_format.getOrElse(throw new IllegalArgumentException("source_format required for FILE type")).toLowerCase;val rdr=spark.read.format(fmt);jobConfig.source_format_options.foreach(o=>JSON.parseFull(o) match {case Some(m:Map[String,String])=>rdr.options(m) case _=>});jobConfig.source_schema.foreach(s=>rdr.schema(s));srcDF=rdr.load(jobConfig.source_connection_details.get) case o=>throw new UnsupportedOperationException(s"Source type '$o' not supported.")}
    if(srcDF==null) throw new RuntimeException("Source DF not loaded.")
    if(jobConfig.audit_level.toUpperCase!="NONE") try rReadCount=Some(srcDF.count()) catch {case e:Exception=>logger.warn(s"Could not count source records for ${jobConfig.job_name}: ${e.getMessage}",e)}\n    logger.info(s"Source data read for ${jobConfig.job_name}. Records: ${rReadCount.getOrElse("N/A")}")
    val viewName=jobConfig.job_name+"_source_view_wl"; srcDF.createOrReplaceTempView(viewName); logger.info(s"Registered source as temp view: '$viewName' for ${jobConfig.job_name}")
    val sql=jobConfig.sql_logic.getOrElse(throw new IllegalArgumentException(s"sql_logic required for WITH_LOGIC mode for ${jobConfig.job_name}"))
    if(sql.trim.isEmpty) throw new IllegalArgumentException(s"sql_logic cannot be empty for ${jobConfig.job_name}")
    val planEither=SqlParserService.parse(sql,spark); val plan=planEither match {case Right(p)=>logger.info(s"SQL parsed for ${jobConfig.job_name}.");p case Left(e)=>throw new RuntimeException(s"Failed to parse SQL for ${jobConfig.job_name}: $e")}\n    LogicalPlanValidator.validate(plan) match {case Right(_)=>logger.info(s"LogicalPlan valid for ${jobConfig.job_name}.") case Left(e)=>throw new RuntimeException(s"LogicalPlan invalid for ${jobConfig.job_name}: ${e.mkString(";")}")}\n    val tDF=try Dataset.ofRows(spark,plan) catch {case e:Exception=>throw new RuntimeException(s"Error generating DF from LogicalPlan for ${jobConfig.job_name}: ${e.getMessage}",e)}\n    logger.info(s"Transformed DF generated for ${jobConfig.job_name}.")
    val wr=tDF.write; jobConfig.target_format.foreach(f=>wr.format(f.toLowerCase)); jobConfig.target_format_options.foreach(o=>JSON.parseFull(o) match {case Some(m:Map[String,String])=>wr.options(m) case _=>}); jobConfig.partitioning_columns.foreach(pc=>{val c=pc.split(',').map(_.trim).filter(_.nonEmpty); if(c.nonEmpty)wr.partitionBy(c:_*) }); val sm=jobConfig.target_write_mode.toLowerCase match {case "overwrite"=>SaveMode.Overwrite case "append"=>SaveMode.Append case "ignore"=>SaveMode.Ignore case "errorifexists"|"error"=>SaveMode.ErrorIfExists case _=>SaveMode.Overwrite}; wr.mode(sm)
    jobConfig.target_type.toUpperCase match {case "HDFS"|"FILE"=>wr.save(jobConfig.target_table_or_path); if(jobConfig.audit_level.toUpperCase!="NONE") try {val tFmt=jobConfig.target_format.getOrElse("parquet");rWrittenCount=Some(spark.read.format(tFmt).load(jobConfig.target_table_or_path).count())} catch {case e:Exception=>logger.warn(s"Could not count written records for ${jobConfig.job_name}: ${e.getMessage}",e)} case o=>throw new UnsupportedOperationException(s"Target type '$o' not supported.")}\n    if(jobConfig.reconciliation_enabled.equalsIgnoreCase("Y")&&jobConfig.reconciliation_config.exists(_.trim.nonEmpty)){logger.info(s"Reconciliation for ${jobConfig.job_name}..."); try {val sRecon=tDF;val tFmt=jobConfig.target_format.getOrElse("parquet"); val tSnap=spark.read.format(tFmt).load(jobConfig.target_table_or_path); val rep=ReconciliationService.executeChecks(jobConfig.job_name,sRecon,tSnap,jobConfig.reconciliation_config.get,spark); logger.info(s"Recon Report for ${jobConfig.job_name}: Status - ${rep.overallStatus}"); rep.checkResults.foreach(cr=>logger.info(s"  Check:${cr.checkType},Status:${cr.status},Msg:${cr.message}")); if(rep.overallStatus!="PASS")logger.warn(s"Recon for ${jobConfig.job_name} status: ${rep.overallStatus}.")} catch {case e:Exception=>logger.error(s"Error during recon for ${jobConfig.job_name}: ${e.getMessage}",e)}}\n    logger.info(s"WITH_LOGIC ingestion for ${jobConfig.job_name} completed. Records written: ${rWrittenCount.getOrElse("N/A")}"); (rReadCount,rWrittenCount)}\n}
