package com.example.etl.api.entity;

import javax.persistence.*;
import java.sql.Timestamp;

@Entity
@Table(name = "JOB_CONFIG_AUDIT_LOG")
public class JobConfigAuditLogEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Assuming log_id is auto-generated by identity
    @Column(name = "log_id")
    private Long logId;

    @Column(name = "job_name", length = 255, nullable = false)
    private String jobName;

    @Column(name = "change_type", length = 50, nullable = false)
    private String changeType; // CREATE, UPDATE, DELETE

    @Column(name = "changed_by_user", length = 100, nullable = false)
    private String changedByUser;

    @Column(name = "change_timestamp", nullable = false)
    private Timestamp changeTimestamp;

    @Lob
    @Column(name = "changed_fields_details")
    private String changedFieldsDetails; // JSON CLOB

    // Constructors
    public JobConfigAuditLogEntity() {
    }

    public JobConfigAuditLogEntity(String jobName, String changeType, String changedByUser, Timestamp changeTimestamp, String changedFieldsDetails) {
        this.jobName = jobName;
        this.changeType = changeType;
        this.changedByUser = changedByUser;
        this.changeTimestamp = changeTimestamp;
        this.changedFieldsDetails = changedFieldsDetails;
    }

    // Getters and Setters (Lombok would be useful here)
    public Long getLogId() { return logId; }
    public void setLogId(Long logId) { this.logId = logId; }
    public String getJobName() { return jobName; }
    public void setJobName(String jobName) { this.jobName = jobName; }
    public String getChangeType() { return changeType; }
    public void setChangeType(String changeType) { this.changeType = changeType; }
    public String getChangedByUser() { return changedByUser; }
    public void setChangedByUser(String changedByUser) { this.changedByUser = changedByUser; }
    public Timestamp getChangeTimestamp() { return changeTimestamp; }
    public void setChangeTimestamp(Timestamp changeTimestamp) { this.changeTimestamp = changeTimestamp; }
    public String getChangedFieldsDetails() { return changedFieldsDetails; }
    public void setChangedFieldsDetails(String changedFieldsDetails) { this.changedFieldsDetails = changedFieldsDetails; }
}
