-- DDL for JOB_CONFIG_AUDIT_LOG table in Oracle
-- This table logs changes made to job configurations via the API.

CREATE TABLE JOB_CONFIG_AUDIT_LOG (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name VARCHAR2(255) NOT NULL, -- The job configuration that was affected
    change_type VARCHAR2(50) NOT NULL, -- e.g., 'CREATE', 'UPDATE', 'DELETE'
    changed_by_user VARCHAR2(100) NOT NULL, -- Username of the person who made the change
    change_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- When the change occurred
    -- Optional: Detailed JSON about what changed. For UPDATEs, could store old/new values.
    -- For simplicity, this can be initially populated with just a summary or key identifiers.
    changed_fields_details CLOB -- JSON string detailing changes (e.g., {"field_name": {"old": "val1", "new": "val2"}})
);

COMMENT ON TABLE JOB_CONFIG_AUDIT_LOG IS 'Logs audit trails of CUD operations on JOB_CONFIG table.';
COMMENT ON COLUMN JOB_CONFIG_AUDIT_LOG.log_id IS 'Unique identifier for the audit log entry (auto-generated).';
COMMENT ON COLUMN JOB_CONFIG_AUDIT_LOG.job_name IS 'The job_name of the JobConfig entity that was created, updated, or deleted.';
COMMENT ON COLUMN JOB_CONFIG_AUDIT_LOG.change_type IS 'Type of change: CREATE, UPDATE, or DELETE.';
COMMENT ON COLUMN JOB_CONFIG_AUDIT_LOG.changed_by_user IS 'User who performed the change.';
COMMENT ON COLUMN JOB_CONFIG_AUDIT_LOG.change_timestamp IS 'Timestamp of when the change was committed.';
COMMENT ON COLUMN JOB_CONFIG_AUDIT_LOG.changed_fields_details IS 'Optional JSON CLOB detailing specific fields changed, with old and new values for UPDATEs.';

-- Optional: Add an index on job_name and change_timestamp for faster querying of a job's history
CREATE INDEX idx_job_config_audit_job_ts ON JOB_CONFIG_AUDIT_LOG (job_name, change_timestamp DESC);
